{ config, pkgs, ... }:
let
  vars = import ./vars.nix;
in {
  imports = [
    ./disko.nix
    # hardware-configuration.nix is generated by nixos-anywhere
    ../../services/adguard-home/nixos.nix
    ../../services/vaultwarden/nixos.nix
    ../../services/gatus/nixos.nix
    ../../services/backup-kopia-b2/nixos.nix
  ];

  # Boot (OCI ARM — iSCSI boot volume)
  boot.initrd.kernelModules = [ "iscsi_tcp" ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "oci-nix";
  networking.firewall.enable = true;

  # Tailscale (host-level)
  services.tailscale.enable = true;

  # Podman (rootful — required by virtualisation.oci-containers)
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    defaultNetwork.settings.dns_enabled = true;
  };
  virtualisation.oci-containers.backend = "podman";

  # User
  users.users.${vars.adminUser} = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = vars.sshKeys;
  };
  nix.settings.trusted-users = [ vars.adminUser ];

  # SSH
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
    };
  };

  # Packages
  environment.systemPackages = with pkgs; [ vim git just ];

  # Nix settings
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # sops-nix global config
  sops.age.keyFile = "/var/lib/sops-nix/age-key.txt";

  system.stateVersion = "24.11";
}
