{ config, pkgs, ... }:
let
  vars = import ./vars.nix;
in
{
  imports = [
    ./disko.nix
    ./hardware-configuration.nix # generated by nixos-anywhere --generate-hardware-config
    ../../services/adguard-home/nixos.nix
    ../../services/vaultwarden/nixos.nix
    ../../services/gatus/nixos.nix
    ../../services/observability # default.nix を暗黙 import
  ];

  # Boot (OCI ARM — UEFI + iSCSI boot volume)
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "virtio_pci"
    "virtio_scsi"
    "usbhid"
    "iscsi_tcp"
  ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "oci-nix";
  networking.useDHCP = true;
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 ];
    trustedInterfaces = [ "tailscale0" ];
  };

  # Tailscale (host-level)
  services.tailscale.enable = true;

  # Podman (rootful — required by virtualisation.oci-containers)
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    defaultNetwork.settings.dns_enabled = true;
  };
  virtualisation.oci-containers.backend = "podman";

  # User
  users.users.root.openssh.authorizedKeys.keys = vars.sshKeys;

  users.users.${vars.adminUser} = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = vars.sshKeys;
  };
  nix.settings.trusted-users = [ vars.adminUser ];

  # SSH
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
    };
  };

  # Journald
  services.journald.extraConfig = ''
    SystemMaxUse=2G
    MaxRetentionSec=180day
  '';

  # Packages
  environment.systemPackages = with pkgs; [
    vim
    git
    jq
    just
  ];

  # Nix settings
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # sops-nix global config
  sops.age.keyFile = "/var/lib/sops-nix/age-key.txt";

  system.stateVersion = "24.11";
}
